services:
  ad-meeting-owen:
    build:
      context: .
    container_name: ad-meeting-owen-service
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb
    volumes:
      - ./.env:/var/www/html/.env
  mongodb:
    image: mongo:latest
    container_name: ad-meeting-owen-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: newodatabase
    ports:
      - "27111:27017"
    volumes:
      - ad-meeting-owen-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: ad-meeting-owen-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newodatabase
    ports:
      - "5112:5432"
    volumes:
      - ad-meeting-owen-postgresql:/data/db/postgresql

volumes:
  ad-meeting-owen-mongodb:
    driver: local
  ad-meeting-owen-postgresql:
    driver: local
